import turtle
turtle.speed(15)
turtle.shape('turtle')

def middle_trianle(x, y,z, length, color_line, color_filling):
    turtle.up()
    turtle.goto(x, y)
    turtle.seth(z)
    turtle.color(color_line, color_filling)
    turtle.begin_fill()
    turtle.forward(2**0.5*length)
    turtle.left(135)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.end_fill()

def square(x,y,z,length,color_line,color_filling):
    turtle.up()
    turtle.goto(x,y)
    turtle.seth(z)
    turtle.color(color_line,color_filling)
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.end_fill()
    turtle.right(45)

def big_trianle(x,y,z,length,color_line,color_filling):
    turtle.up()
    turtle.goto(x,y)
    turtle.seth(z)
    turtle.down()
    turtle.color(color_line,color_filling)
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(135)
    turtle.forward((length**2/2)**0.5)
    turtle.left(90)
    turtle.forward((length**2/2)**0.5)
    turtle.right(135)
    turtle.end_fill()

def parallelogramm_2(x, y, z, length, color_line, color_filling):
    turtle.up()
    turtle.goto(x, y)
    turtle.seth(z)
    turtle.color(color_line, color_filling)
    turtle.begin_fill()
    turtle.forward(length/ 2 * 2 ** 0.5)
    turtle.left(45)
    turtle.forward(length)
    turtle.left(135)
    turtle.forward(length/ 2 * 2 ** 0.5)
    turtle.left(45)
    turtle.forward(length)
    turtle.end_fill()

def hare(k,l):
    middle_trianle(k, l, 90, 60, "white", "salmon")
    parallelogramm_2(k+1, l, 10, 60, "white", "darkred")
    square(k+1, l-1, -90, 40, "white", "sienna")
    middle_trianle(k, l-155, 90, 100, "white", "tomato")
    big_trianle(k+41, l-198, 135, 160, "white", "sandybrown")
    big_trianle(k, l - 40, -90, 60, "white", "orange")
    middle_trianle(k+31, l-131, 90, 60/2**0.5, "white", "goldenrod")
  
hare(-200,200)
turtle.exitonclick()
turtle.done()
