import turtle
turtle.speed(15)
turtle.shape('turtle')

def middle_trianle(x, y,z, length, color_line, color_filling):
    turtle.up()
    turtle.goto(x, y)
    turtle.seth(z)
    turtle.color(color_line, color_filling)
    turtle.begin_fill()
    turtle.forward(2**0.5*length)
    turtle.left(135)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.end_fill()

def square(x,y,z,length,color_line,color_filling):
    turtle.up()
    turtle.goto(x,y)
    turtle.seth(z)
    turtle.color(color_line,color_filling)
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.end_fill()
    turtle.right(45)

def big_trianle(x,y,z,length,color_line,color_filling):
    turtle.up()
    turtle.goto(x,y)
    turtle.seth(z)
    turtle.down()
    turtle.color(color_line,color_filling)
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(135)
    turtle.forward((length**2/2)**0.5)
    turtle.left(90)
    turtle.forward((length**2/2)**0.5)
    turtle.right(135)
    turtle.end_fill()

def parallelogramm_2(x, y, z, length, color_line, color_filling):
    turtle.up()
    turtle.goto(x, y)
    turtle.seth(z)
    turtle.color(color_line, color_filling)
    turtle.begin_fill()
    turtle.forward(length/ 2 * 2 ** 0.5)
    turtle.left(45)
    turtle.forward(length)
    turtle.left(135)
    turtle.forward(length/ 2 * 2 ** 0.5)
    turtle.left(45)
    turtle.forward(length)
    turtle.end_fill()

def hare(k,l):
    middle_trianle(k, l, 90, 40, "white", "salmon")
    parallelogramm_2(k + 1, l, 10, 40, "white", "darkred")
    square(k + 1, l -0.5, -90, 40 / 1.5, "white", "sienna")
    big_trianle(k, l - 26, -90, 40, "white", "orange")
    middle_trianle(k + 21, l - 86, 90, 40 / 2 ** 0.5, "white", "goldenrod")
    middle_trianle(k, l - 86, 90, 80 / 1.5, "white", "tomato")
    big_trianle(k + 22, l - 108.5, 135, 130 / 1.5, "white", "sandybrown")
  
hare(-200,200)
turtle.exitonclick()
turtle.done()
