import turtle
turtle.speed(15)
turtle.shape('turtle')

def middle_trianle(x, y,z, length, color_line, color_filling):
    turtle.up()
    turtle.goto(x, y)
    turtle.seth(z)
    turtle.color(color_line, color_filling)
    turtle.begin_fill()
    turtle.forward(2**0.5*length)
    turtle.left(135)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.end_fill()

def square(x,y,z,length,color_line,color_filling):
    turtle.up()
    turtle.goto(x,y)
    turtle.seth(z)
    turtle.color(color_line,color_filling)
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.end_fill()
    turtle.right(45)

def parallelogramm_2(x, y, z, length, color_line, color_filling):
    turtle.up()
    turtle.goto(x, y)
    turtle.seth(z)
    turtle.color(color_line, color_filling)
    turtle.begin_fill()
    turtle.forward(length/ 2 * 2 ** 0.5)
    turtle.left(45)
    turtle.forward(length)
    turtle.left(135)
    turtle.forward(length/ 2 * 2 ** 0.5)
    turtle.left(45)
    turtle.forward(length)
    turtle.end_fill()

def seal(k,l):
    middle_trianle(k, l, -30, 60, "white", "aquamarine")
    square(k+14.7, l-58.3, -30, 60/(2**0.5), "white", "aqua")
    middle_trianle(k+14, l-59, -75, 60/2**0.5, "white", "mediumslateblue")
    parallelogramm_2(k+14, l-61, -120, 57, "white", "lightskyblue")
    middle_trianle(k + 105, l - 158, 105, 60 * 2 ** 0.5, "white", "springgreen")
    middle_trianle(k + 188, l - 136, 150, 60 * 2 ** 0.5, "white", "deepskyblue")
    middle_trianle(k+211, l-100, 194, 60/2**0.5, "white", "mediumslateblue")

seal(-200,200)
turtle.exitonclick()
turtle.done()
